# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1I3S-pAv_Y6X10DThL98HNCQ99EwKy87_
"""

import streamlit as st
import pickle
import pandas as pd

st.caption("Sleep Disorder Assessment")
st.markdown("<h3>Please answer the following questions regarding your sleeping habits:</h3>", unsafe_allow_html=True)

col1, col2, col3 = st.columns(3)

# Getting user input for sleep questionnaire
q1 = col1.selectbox("1. Do you have difficulty falling asleep?", ["Never", "Occasionally", "Mostly", "Always"])
q2 = col2.selectbox("2. Do you wake up frequently during the night?", ["Never", "Occasionally", "Mostly", "Always"])
q3 = col3.selectbox("3. Do you wake up earlier than intended and struggle to sleep again?", ["Never", "Occasionally", "Mostly", "Always"])

q4 = col1.selectbox("4. Do you experience excessive sleepiness during the daytime?", ["Never", "Occasionally", "Mostly", "Always"])
q5 = col2.selectbox("5. Do you feel that your sleep-wake cycle is irregular?", ["Never", "Occasionally", "Mostly", "Always"])
q6 = col3.selectbox("6. Do you feel unrefreshed even after a full night's sleep?", ["Never", "Occasionally", "Mostly", "Always"])

q7 = col1.selectbox("7. Do you snore during sleep?", ["Never", "Occasionally", "Mostly", "Always"])
q8 = col2.selectbox("8. Do you wake up with headaches in the morning?", ["Never", "Occasionally", "Mostly", "Always"])
q9 = col3.selectbox("9. Do you experience restless legs or involuntary movements?", ["Never", "Occasionally", "Mostly", "Always"])

q10 = col1.selectbox("10. Do you experience choking or gasping while sleeping?", ["Never", "Occasionally", "Mostly", "Always"])

btn = st.button("Predict", type="primary")

# Create DataFrame
df_pred = pd.DataFrame([[q1, q2, q3, q4, q5, q6, q7, q8, q9, q10]],
    columns=['q1','q2','q3','q4','q5','q6','q7','q8','q9','q10'])

# Transform function for responses
def transform(response):
    if response == "Never":
        return 0
    elif response == "Occasionally":
        return 1
    elif response == "Mostly":
        return 2
    elif response == "Always":
        return 3

# Apply transformation
for col in df_pred.columns:
    df_pred[col] = df_pred[col].apply(transform)

# Load sleep prediction model
with open('svm_model.pkl', 'rb') as file:
    svm_model = pickle.load(file)

# Prediction
prediction = svm_model.predict(df_pred)

if btn:
    st.write("<b>Sleep Disorder Detected:</b>", prediction[0], unsafe_allow_html=True)
